/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollo;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Operaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n1, n2;
        String[] operaciones = {"Suma", "Resta", "Multiplicación", "División"};
        String valor = (String) JOptionPane.showInputDialog(this, "Ingresar", "Operaciones basicas", JOptionPane.INFORMATION_MESSAGE, null, operaciones, operaciones[0]);

        if (valor.equalsIgnoreCase("Suma")) {
            n1 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 1er valor:"));
            n2 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 2º valor:"));
            JOptionPane.showMessageDialog(this, "La suma es: " + (n1 + n2));
        } else if (valor.equalsIgnoreCase("Resta")) {
            n1 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 1er valor:"));
            n2 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 2º valor:"));
            JOptionPane.showMessageDialog(this, "La resta es: " + (n1 - n2));
        } else if (valor.equalsIgnoreCase("Multiplicación")) {
            n1 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 1er valor:"));
            n2 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 2º valor:"));
            JOptionPane.showMessageDialog(this, "La multiplicación es: " + (n1 * n2));
        } else if (valor.equalsIgnoreCase("División")) {
            n1 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 1er valor:"));
            n2 = Integer.parseInt(JOptionPane.showInputDialog("Ingresar 2º valor:"));
            JOptionPane.showMessageDialog(this, "La división es: " + (n1 / n2));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
